/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.machine.domain;

/**
 *
 * @author user
 */
public class WindowsMachine extends javax.swing.JFrame {
    
    //Atributos
    private Machine maquina;
  
    /**
     * Creates new form WindowsMachine
     */
    public WindowsMachine() {
        initComponents();
        //CODIGO 
        
        //CREAR UN REFRESCO Y LA MAQUINA PASANDO EL REFRESCO
        //Machine maquinilla new = Machine();
        Refresco r = new Refresco(50, "Pepsi", 3, 22.5);
        this.maquina =  new Machine("m1", r);
        
        this.labelTitle.setText("Maquina de " + r.getSabor());
        
        //PROCEDIMIENTOS
        refrescar_stock();
        
    }
    
    private void refrescar_stock(){
        int cantidadDisponible = this.maquina.getRefrescosDisponibles();
        System.out.println("... hay " + cantidadDisponible + "refresco");
        if(cantidadDisponible > 0){
            this.labelNoAgotado.setVisible(true);
            this.labelAgotado.setVisible(false);
        }
        else{
            this.labelNoAgotado.setVisible(false);
            this.labelAgotado.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelNoAgotado = new javax.swing.JLabel();
        labelAgotado = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        labelDisplay = new javax.swing.JLabel();
        btnEstado = new javax.swing.JButton();
        labelEstado = new javax.swing.JLabel();
        labelctnreponer = new javax.swing.JLabel();
        textFieldRepo = new javax.swing.JTextField();
        btnReponer = new javax.swing.JButton();
        labelOptionRepo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maquina exprendedora");

        labelTitle.setText("Maquina de ");

        labelNoAgotado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNoAgotado.setForeground(new java.awt.Color(0, 204, 0));
        labelNoAgotado.setText("*");

        labelAgotado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAgotado.setForeground(new java.awt.Color(255, 0, 0));
        labelAgotado.setText(" *");
        labelAgotado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        labelDisplay.setBackground(new java.awt.Color(255, 255, 255));

        btnEstado.setText("Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        labelEstado.setBackground(new java.awt.Color(204, 204, 204));
        labelEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelctnreponer.setText("Cantidad a reponer:");

        textFieldRepo.setText("*");

        btnReponer.setText("Reponer");
        btnReponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReponerActionPerformed(evt);
            }
        });

        labelOptionRepo.setBackground(new java.awt.Color(0, 0, 0));
        labelOptionRepo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelctnreponer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNoAgotado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAgotado)
                                .addGap(44, 44, 44)
                                .addComponent(btnComprar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(textFieldRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelOptionRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(btnReponer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEstado)
                                .addGap(27, 27, 27)
                                .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNoAgotado)
                        .addComponent(labelAgotado)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelctnreponer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReponer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOptionRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        //VENDER UNA LATA
        boolean vendido = this.maquina.vender();
       
        if(vendido){
            //display - Refresco entregado !! Disfrute !!! 
            this.labelDisplay.setText("Refresco entregado !! Disfrute !!! ");
        }
        else{
            this.labelDisplay.setText("Refresco agotado");
            //display - Refresco agotado
        }
        
        refrescar_stock();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        this.labelEstado.setText(this.maquina.toString());
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnReponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReponerActionPerformed
        
        //1. leer valor entrada cantidad a reponer (String)
        String cantReponer = this.textFieldRepo.getText();
        System.out.println("Hemos leido dato " + cantReponer);
        //2. convertir el string en un int
        
        //int cantReponerInt = Int
        int cantidad = 0;
        try{
            cantidad = Integer.parseInt(cantReponer); 
            System.out.println("... cantidad convertida a int es " + cantidad);
            this.labelOptionRepo.setText("Valor correcto");
            //3. llamar a maquina refresco y añadir nuevas latas
            this.maquina.reponer(cantidad);
            //4. refrescar
            this.refrescar_stock();
            //5. En el display mostrar resultado
            this.labelDisplay.setText("Reposicion completa!!!!");
            
        }
        catch(NumberFormatException e){
            this.labelOptionRepo.setText("Error al Reponer. Introduzca una cantidad valida");
        }
        
    }//GEN-LAST:event_btnReponerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnReponer;
    private javax.swing.JLabel labelAgotado;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNoAgotado;
    private javax.swing.JLabel labelOptionRepo;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelctnreponer;
    private javax.swing.JTextField textFieldRepo;
    // End of variables declaration//GEN-END:variables
}
